<?php

namespace App\Modules\Commerce\Filament\Resources\Orders\Tables;

use App\Modules\Commerce\Enums\OrderStatus;
use Filament\Actions\ViewAction;
use Filament\Forms\Components\Select;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Filters\Filter;
use Filament\Tables\Filters\SelectFilter;
use Filament\Tables\Filters\TernaryFilter;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;

/**
 * List-only (§1 of the approved brief) — Orders are system-generated by
 * CreatePendingOrderAction/MarkOrderPaidAction, never hand-created/edited in
 * the admin panel.
 */
class OrdersTable
{
    public static function configure(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('public_id')
                    ->label('Order #')
                    ->searchable()
                    ->copyable(),
                TextColumn::make('purchaser_email')
                    ->label('Purchaser')
                    ->searchable()
                    ->description(fn ($record): string => $record->user_id === null ? 'Guest' : 'Registered'),
                TextColumn::make('items.item_title')
                    ->label('Item')
                    ->listWithLineBreaks(),
                TextColumn::make('total')
                    ->money('usd')
                    ->sortable(),
                TextColumn::make('status')
                    ->badge()
                    ->sortable(),
                TextColumn::make('payment_provider')
                    ->label('Provider')
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('created_at')
                    ->label('Placed')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('paid_at')
                    ->dateTime()
                    ->sortable()
                    ->placeholder('—'),
            ])
            ->filters([
                SelectFilter::make('status')->options(OrderStatus::options()),
                TernaryFilter::make('user_id')
                    ->label('Purchaser type')
                    ->nullable()
                    ->trueLabel('Registered')
                    ->falseLabel('Guest')
                    ->placeholder('All'),
                Filter::make('item_type')
                    ->schema([
                        Select::make('type')
                            ->options(['album' => 'Album', 'single' => 'Single'])
                            ->placeholder('All'),
                    ])
                    ->query(fn (Builder $query, array $data): Builder => match ($data['type'] ?? null) {
                        'album' => $query->whereHas('items', fn ($q) => $q->whereNotNull('album_id')),
                        'single' => $query->whereHas('items', fn ($q) => $q->whereNotNull('single_id')),
                        default => $query,
                    }),
            ])
            ->recordActions([
                ViewAction::make(),
            ])
            ->toolbarActions([])
            ->defaultSort('created_at', 'desc')
            ->paginationPageOptions([10, 25, 50, 'all'])
            ->defaultPaginationPageOption(25);
    }
}
