; Production PHP settings
upload_max_filesize = 520M
post_max_size = 520M
memory_limit = 512M
max_execution_time = 120
max_input_time = 120
variables_order = "GPCS"

opcache.enable=1
opcache.validate_timestamps=0
opcache.memory_consumption=128
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=20000
opcache.revalidate_freq=0
